name: CI

on:
  push:
    branches: [ topic/actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build -- --prod
      - run: npx scully
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Zip artifacts
        run: |
          cd ./dist/static
          zip -r ${{ steps.package-version.outputs.current-version }} .
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ steps.package-version.outputs.current-version }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/Mogyuchi/mogyuchi.com/releases/${{ steps.package-version.outputs.current-version }}/assets
          asset_path: ./dist/static/${{ steps.package-version.outputs.current-version}}.zip
